<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Downloadexcel extends CI_Controller {
    public function __construct(){
        parent::__construct();
        $this->load->model('M_admin');
        $this->load->model('M_pendaftaran');
    }

    public function to_excel(){
        require(APPPATH.'third_party/PHPExcel-1.8/Classes/PHPExcel.php');
        require(APPPATH.'third_party/PHPExcel-1.8/Classes/PHPExcel/Writer/Excel2007.php');

        $objPHPExcel = new PHPExcel();

        $objPHPExcel->getProperties()->setCreator("Ismo Broto")
            ->setLastModifiedBy("Ismo Broto")
            ->setTitle("Export PHPExcel Test Document")
            ->setSubject("Export PHPExcel Test Document")
            ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
            ->setKeywords("office 2007 openxml php")
            ->setCategory("PHPExcel");
      
        $objPHPExcel->setActiveSheetIndex(0);

        $objPHPExcel->getActiveSheet()->SetCellValue('A1','test');
        $objPHPExcel->getActiveSheet()->SetCellValue('B1','test2');

        $objPHPExcel->getActiveSheet()->SetCellValue('A2','test22');
        $objPHPExcel->getActiveSheet()->SetCellValue('B2','test22');

        $objPHPExcel->getActiveSheet()->setTitle('Data Peserta');
        
        $objWriter  = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        header('Last-Modified:'. gmdate("D, d M Y H:i:s").'GMT');
        header('Chace-Control: no-store, no-cache, must-revalation');
        header('Chace-Control: post-check=0, pre-check=0', FALSE);
        header('Pragma: no-cache');
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="ExportDataOrangPHPExcel'. date('Ymd') .'.xlsx"');
        
        $objWriter->save('php://output');
    }
}